name: Deploy Application

on:
  workflow_run:
    workflows:
      - Test Application
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # - name: Instalar AWS CLI v2
      #   run: |
      #     sudo apt-get remove -y awscli || true
      #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      #     unzip awscliv2.zip
      #     sudo ./aws/install --update

      - name: Configurar Credenciales de AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Dar permisos a gradlew
        run: chmod +x gradlew

      - name: Desplegar con CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name "Studentify_GithubActions" \
            --deployment-group-name "GrupoStudentify" \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}