name: Deploy Test Application

on:
  workflow_run:
    workflows: 
      - "Test Application"
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu22.04
    permissions:
        contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          audience: sts.amazonaws.com
          role-skip-session-tagging: true